import React, { ReactNode } from 'react';
import Head from 'next/head';
import Header from './Header';

const Container = ({ children }: { children: ReactNode }) => {
  return (
    <>
      <Head>
        <title>MY TO DO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex justify-center items-center w-full px-10">
          <Header />
          <>{children}</>
        </div>
      </main>
    </>
  );
};

export default Container;
